# Generated by Django 4.2.7 on 2024-01-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.TextField(max_length=200)),
                ('producto', models.TextField(max_length=200)),
                ('codigo', models.IntegerField()),
                ('indice', models.FloatField()),
                ('precio', models.IntegerField()),
                ('antireflejo', models.TextField(max_length=10)),
                ('filtro_azul', models.TextField(max_length=10)),
                ('fotocromatica', models.TextField(max_length=10)),
                ('polarizado', models.TextField(max_length=10)),
                ('esfera', models.FloatField()),
                ('cilindro', models.FloatField()),
                ('material', models.CharField(choices=[('Policarbonato', 'Policarbonato'), ('Mineral', 'Mineral'), ('Organico', 'Orgánico')], max_length=100)),
            ],
        ),
    ]
