# Generated by Django 4.2.7 on 2024-03-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lentes',
            name='cristal',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
